// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_owxwS_bv_2L6L3ZcwGLgxj2bt4Uf048',
    appId: '1:343437523149:web:5043e3f323110a3c989184',
    messagingSenderId: '343437523149',
    projectId: 'fir-e6746',
    authDomain: 'fir-e6746.firebaseapp.com',
    storageBucket: 'fir-e6746.appspot.com',
    measurementId: 'G-ZCBSJKBJ6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIgnQqtEdeeqbCUHflb-zsD0LbqzgWTMs',
    appId: '1:343437523149:android:63465d539dad772b989184',
    messagingSenderId: '343437523149',
    projectId: 'fir-e6746',
    storageBucket: 'fir-e6746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuQEXtpqKWKTSykXAN2weLGsuQ4_T0kvA',
    appId: '1:343437523149:ios:75643955fe90a32f989184',
    messagingSenderId: '343437523149',
    projectId: 'fir-e6746',
    storageBucket: 'fir-e6746.appspot.com',
    iosBundleId: 'com.teachese.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuQEXtpqKWKTSykXAN2weLGsuQ4_T0kvA',
    appId: '1:343437523149:ios:75643955fe90a32f989184',
    messagingSenderId: '343437523149',
    projectId: 'fir-e6746',
    storageBucket: 'fir-e6746.appspot.com',
    iosBundleId: 'com.teachese.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_owxwS_bv_2L6L3ZcwGLgxj2bt4Uf048',
    appId: '1:343437523149:web:34546ec132767bda989184',
    messagingSenderId: '343437523149',
    projectId: 'fir-e6746',
    authDomain: 'fir-e6746.firebaseapp.com',
    storageBucket: 'fir-e6746.appspot.com',
    measurementId: 'G-6BXG4VTBR6',
  );
}
